const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base='http://127.0.0.1:19401',password='QaFixtureOnly-123456',setupToken='QaSetupOnly-'.repeat(4);
(async()=>{
 const browser=await chromium.launch({headless:true}),contexts=[],errors=[];
 async function page(){const context=await browser.newContext({viewport:{width:1280,height:900}});contexts.push(context);const p=await context.newPage();p.on('pageerror',error=>errors.push(error.message));return p;}
 const owner=await page();
 async function fill(p,values){for(const [label,value]of Object.entries(values))await p.getByLabel(label,{exact:true}).fill(value);}
 async function click(p,name){await p.getByRole('button',{name,exact:true}).last().click();}
 async function heading(p,name){await p.getByRole('heading',{name,exact:true}).waitFor();}
 async function section(p,name){await p.getByRole('navigation').getByRole('button',{name,exact:true}).click();await p.getByRole('heading',{name,exact:true,level:1}).waitFor();await p.locator('#app[aria-busy="false"]').waitFor();}
 async function until(condition){for(let i=0;i<100;i++){if(await condition())return;await new Promise(resolve=>setTimeout(resolve,100));}throw new Error('Browser state did not settle');}
 try{
  const health=await (await owner.request.get(base+'/api/health/ready')).json();assert.equal(health.revision,process.env.BROWSER_QA_REVISION,'Disposable checked image identity');
  await owner.goto(base);await heading(owner,'Welcome to Bowin');await owner.getByLabel('Email',{exact:true}).focus();await owner.keyboard.press('Tab');assert.equal(await owner.getByLabel('Password',{exact:true}).evaluate(node=>node===document.activeElement),true);
  await click(owner,'Initial setup');await fill(owner,{'Email':'browser-owner@example.invalid','Your name':'Browser Organizer','Password':password,'Organization name':'Browser Tournament Club','Setup token':setupToken});await click(owner,'Initial setup');await heading(owner,'Tournaments');
  await fill(owner,{'Tournament name':'Browser Championship','Venue':'QA Gym','Event date':'2027-02-28','Time zone':'America/Toronto'});await click(owner,'Create tournament');await heading(owner,'Browser Championship');
  await section(owner,'Divisions');for(const [name,type]of [['Browser Sparring','sparring'],['Browser Patterns','patterns']]){await owner.getByLabel('Division name',{exact:true}).fill(name);await owner.getByLabel('Discipline',{exact:true}).selectOption(type);await click(owner,'Add division');await heading(owner,name);}
  await section(owner,'Registration');const names=['Private <img src=x onerror="window.qaXss=true">','Private Browser B'];
  for(let i=0;i<2;i++){await fill(owner,{'Competitor name':names[i],'Club':'Private Browser Club','Public display name':'Browser Athlete '+(i?'B':'A')});await click(owner,'Add competitor');await heading(owner,names[i]);}
  assert.equal(await owner.evaluate(()=>window.qaXss),undefined);
  for(const name of names)for(const division of ['Browser Sparring','Browser Patterns']){await owner.getByLabel('Competitor',{exact:true}).selectOption({label:name});await owner.getByLabel('Division',{exact:true}).selectOption({label:division});await click(owner,'Register competitor');await until(async()=>(await owner.getByRole('article').filter({has:owner.getByRole('heading',{name,exact:true})}).getByText(division,{exact:true}).count())===1);}
  for(let remaining=4;remaining>0;remaining--){await owner.getByRole('button',{name:'Check in',exact:true}).first().click();await until(async()=>(await owner.getByRole('button',{name:'Check in',exact:true}).count())===remaining-1);}
  await section(owner,'Schedule');await owner.getByLabel('Division',{exact:true}).selectOption({label:'Browser Sparring'});await fill(owner,{'Ring':'Ring A','Start time (UTC)':'2027-02-28T14:00','Duration in minutes':'30'});await click(owner,'Book ring');await heading(owner,'Browser Sparring');
  await section(owner,'Team');await fill(owner,{'Invite email':'browser-scorekeeper@example.invalid'});await owner.getByLabel('Invite role',{exact:true}).selectOption('scorekeeper');await click(owner,'Create invitation');const link=await owner.getByLabel('Invitation link',{exact:true}).inputValue();assert.match(link,/\/accept-invite#[a-f0-9]{64}$/);
  const staff=await page();await staff.goto(link);await heading(staff,'Accept invitation');assert.equal(new URL(staff.url()).hash,'');await fill(staff,{'Your name':'Browser Scorekeeper','Password':password});await click(staff,'Accept invitation');await heading(staff,'Scoring');assert.equal(await staff.getByRole('navigation').getByRole('button').count(),1);for(const name of ['Team','Registration','Results'])assert.equal(await staff.getByRole('navigation').getByRole('button',{name,exact:true}).count(),0);
  await section(owner,'Scoring');const sparring=owner.getByRole('article').filter({has:owner.getByRole('heading',{name:'Browser Sparring',exact:true})});await sparring.getByRole('button',{name:'Move '+names[0]+' down',exact:true}).click();await sparring.getByRole('button',{name:'Move '+names[0]+' up',exact:true}).click();await sparring.getByRole('button',{name:'Generate bracket',exact:true}).click();await sparring.getByRole('heading',{name:'Round 1 · Match 1',exact:true}).waitFor();
  await click(owner,'Start patterns final');await until(async()=>(await owner.getByRole('button',{name:'Start patterns final',exact:true}).count())===0);await click(owner,'Complete patterns final');await owner.getByRole('status').getByText('Record a score for every entrant before completing.',{exact:true}).waitFor();
  assert.equal(new URL(staff.url()).pathname,'/');await staff.reload();await heading(staff,'Scoring');assert.equal(await staff.getByRole('button',{name:'Complete patterns final',exact:true}).count(),0);await fill(staff,{'Left score':'3','Right score':'1'});await staff.getByRole('article').filter({has:staff.getByRole('heading',{name:'Browser Sparring',exact:true})}).getByRole('button',{name:'Record score',exact:true}).click();await staff.getByText('Champion: '+names[0],{exact:true}).waitFor();
  for(const name of names){const row=staff.getByRole('article').filter({has:staff.getByRole('heading',{name:'Browser Patterns',exact:true})}).getByRole('heading',{name,exact:true}).locator('..');await row.getByLabel('Aggregate score (0–10)',{exact:true}).fill('9.00');await row.getByRole('button',{name:'Record score',exact:true}).click();await row.getByText('Score: 9.00',{exact:true}).waitFor();}
  await click(owner,'Complete patterns final');await owner.getByRole('status').getByText('A score changed while you were working. Refresh and try again.',{exact:true}).waitFor();await owner.locator('#app[aria-busy="false"]').waitFor();assert.equal(await owner.getByText('Score: 9.00',{exact:true}).count(),2);await section(owner,'Scoring');await click(owner,'Complete patterns final');await heading(owner,'Final rankings');assert.equal(await owner.getByText(/^Rank 1:/).count(),2);
  await section(owner,'Results');await click(owner,'Publish results');const results=owner.getByRole('link',{name:'View public results',exact:true});await results.waitFor();const publicUrl=await results.getAttribute('href'),publicPage=await page();await publicPage.goto(publicUrl);await heading(publicPage,'Browser Championship');await publicPage.getByText('Champion: Browser Athlete A',{exact:true}).waitFor();assert.equal(await publicPage.getByText(/^Rank 1:/).count(),2);const publicText=await publicPage.locator('body').innerText();for(const privateValue of [...names,'Private Browser Club','browser-owner@example.invalid','Browser Scorekeeper'])assert.ok(!publicText.includes(privateValue));
  await click(owner,'Withdraw public results');await until(async()=>(await owner.getByRole('link',{name:'View public results',exact:true}).count())===0);await publicPage.reload();await heading(publicPage,'Results unavailable');
  await owner.setViewportSize({width:390,height:844});await section(owner,'Scoring');assert.ok(await owner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await owner.screenshot({path:'bowin-browser-mobile.png',fullPage:true});
  await click(owner,'Sign out');await heading(owner,'Welcome to Bowin');assert.equal(await owner.getByText(names[0],{exact:true}).count(),0);await fill(owner,{'Email':'browser-owner@example.invalid','Password':password});await click(owner,'Sign in');await heading(owner,'Tournaments');await heading(owner,'Browser Championship');await owner.setViewportSize({width:1280,height:900});await owner.screenshot({path:'bowin-browser-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);const proof={status:'passed',revision:health.revision,owner_bootstrap:true,tournament_and_divisions:true,registration_and_check_in:true,schedule_booking:true,staff_invitation:true,staff_controls_scoped:true,invitation_reload_session:true,seed_reordering:true,sparring_completion:true,patterns_ties_and_completion:true,incomplete_patterns_rejected:true,stale_completion_rejected_and_refreshed:true,public_alias_privacy:true,publication_withdrawal:true,text_safe_names:true,keyboard_labels:true,mobile_no_overflow:true,logout_clears_data:true,signin_persists_event:true,page_errors:errors,local_qa_cookie_exception:true,production_mutated:false};fs.writeFileSync('bowin-browser-verification.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
 }catch(error){await owner.screenshot({path:'bowin-browser-failure.png',fullPage:true}).catch(()=>{});console.error(error);process.exitCode=1;}finally{for(const context of contexts)await context.close();await browser.close();}
})();
