import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {createApp} from '../src/app.mjs';
const connection=process.env.DATABASE_URL;
test('Fresh setup, sessions, registration/check-in and tenant/role boundaries',{skip:!connection},async()=>{
  assert.match(new URL(connection).pathname,/^\/bowin_rebuild_qa_[a-z0-9_]+$/);
  const pool=new pg.Pool({connectionString:connection});
  const origin='https://qa.example.invalid',setupToken='QaSetupOnly-'.repeat(4);
  const app=createApp({pool,origin,setupToken,revision:'a'.repeat(40)});
  const server=app.listen(0,'127.0.0.1');
  await new Promise(resolve=>server.on('listening',resolve));
  const base=`http://127.0.0.1:${server.address().port}`;
  const fixture={email:'owner@example.invalid',name:'QA owner',organization:'QA tournament club',password:'QaFixtureOnly-123456',setupToken};
  async function request(path,{method='GET',body,cookie,requestOrigin=origin}={}){
    return fetch(base+path,{method,headers:{origin:requestOrigin,'content-type':'application/json',...(cookie?{cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  }
  try {
    assert.equal((await pool.query('SELECT 1 FROM bowin_rebuild.users')).rowCount,0,'Test database must start empty');
    assert.equal((await request('/api/auth/bootstrap',{method:'POST',body:fixture,requestOrigin:'https://foreign.example.invalid'})).status,403);
    assert.equal((await request('/api/auth/bootstrap',{method:'POST',body:{...fixture,setupToken:'wrong'}})).status,403);
    const setup=await request('/api/auth/bootstrap',{method:'POST',body:fixture});
    assert.equal(setup.status,201);
    const organizationId=(await setup.json()).organizationId;
    const session=setup.headers.get('set-cookie');
    assert.match(session,/HttpOnly/);assert.match(session,/Secure/);assert.match(session,/SameSite=Strict/);
    const cookie=session.split(';')[0];
    assert.equal((await request('/api/auth/bootstrap',{method:'POST',body:fixture})).status,409);
    assert.equal((await request('/api/me')).status,401);
    const me=await request('/api/me',{cookie});assert.equal(me.status,200);
    const userId=(await me.json()).user.id;
    const invitePath=`/api/organizations/${organizationId}/invites`;
    const invitation=await request(invitePath,{method:'POST',cookie,body:{email:'scorekeeper@example.invalid',role:'scorekeeper'}});
    assert.equal(invitation.status,201);
    const invite=(await invitation.json()).inviteUrl;
    const inviteToken=invite.split('#')[1];
    const acceptance={token:inviteToken,name:'QA scorekeeper',password:'QaScorekeeperOnly-123456'};
    const accepted=await request('/api/auth/accept-invite',{method:'POST',body:acceptance});assert.equal(accepted.status,201);
    const scoreCookie=accepted.headers.get('set-cookie').split(';')[0];
    assert.equal((await request('/api/auth/accept-invite',{method:'POST',body:acceptance})).status,404);
    assert.equal((await request(invitePath,{method:'POST',cookie:scoreCookie,body:{email:'unauthorized@example.invalid',role:'organizer'}})).status,403);
    const path=`/api/organizations/${organizationId}/tournaments`;
    const payload={name:'QA Championship',venue:'QA Gym',eventDate:'2027-02-28',timeZone:'America/Toronto'};
    assert.equal((await request(path,{method:'POST',cookie,body:{...payload,eventDate:'2027-02-29'}})).status,400);
    const created=await request(path,{method:'POST',cookie,body:payload});assert.equal(created.status,201);
    const tournamentId=(await created.json()).id;
    const tournamentPath=path+'/'+tournamentId;
    const listed=await request(path,{cookie});assert.equal((await listed.json()).tournaments.length,1);
    assert.equal((await request('/api/health/ready')).status,200);
    const divisionBody={name:'QA sparring',discipline:'sparring',format:'single_elimination'};
    assert.equal((await request(tournamentPath+'/divisions',{method:'POST',cookie,body:{...divisionBody,format:'scored_final'}})).status,400);
    const division=await request(tournamentPath+'/divisions',{method:'POST',cookie,body:divisionBody});assert.equal(division.status,201);
    const divisionId=(await division.json()).id;
    const scheduleBody={ring:'Ring A',startsAt:'2027-02-28T10:00:00.000Z',durationMinutes:30};
    const schedulePath=tournamentPath+`/divisions/${divisionId}/schedule`;
    assert.equal((await request(schedulePath,{method:'POST',cookie:scoreCookie,body:scheduleBody})).status,403);
    assert.equal((await request(schedulePath,{method:'POST',cookie,body:{...scheduleBody,startsAt:'2027-03-01T10:00:00.000Z'}})).status,409);
    assert.equal((await request(schedulePath,{method:'POST',cookie,body:scheduleBody})).status,200);
    // March 1 in UTC is still February 28 in the organizer's time zone.
    assert.equal((await request(schedulePath,{method:'POST',cookie,body:{...scheduleBody,startsAt:'2027-03-01T00:00:00.000Z'}})).status,200);
    assert.equal((await request(schedulePath,{method:'POST',cookie,body:scheduleBody})).status,200);
    const extraDivisions=[];
    for(const name of ['QA patterns A','QA patterns B']){
      const extra=await request(tournamentPath+'/divisions',{method:'POST',cookie,body:{name,discipline:'patterns',format:'scored_final'}});
      assert.equal(extra.status,201);extraDivisions.push((await extra.json()).id);
    }
    const secondSchedule=tournamentPath+`/divisions/${extraDivisions[0]}/schedule`;
    assert.equal((await request(secondSchedule,{method:'POST',cookie,body:{...scheduleBody,ring:'ring a'}})).status,409);
    assert.equal((await request(secondSchedule,{method:'POST',cookie,body:{...scheduleBody,startsAt:'2027-02-28T10:30:00.000Z'}})).status,200);
    const raceBooking=await Promise.all(extraDivisions.map(id=>request(tournamentPath+`/divisions/${id}/schedule`,{method:'POST',cookie,body:{...scheduleBody,ring:'Ring B'}})));
    assert.deepEqual(raceBooking.map(response=>response.status).sort(),[200,409]);
    const competitorBody={name:'Private QA competitor',club:'QA club',publicDisplayName:'QA athlete A'};
    const competitor=await request(tournamentPath+'/competitors',{method:'POST',cookie,body:competitorBody});assert.equal(competitor.status,201);
    const competitorId=(await competitor.json()).id;
    const registrationBody={competitorId,divisionId};
    const registration=await request(tournamentPath+'/registrations',{method:'POST',cookie,body:registrationBody});assert.equal(registration.status,201);
    const registrationId=(await registration.json()).id;
    assert.equal((await request(tournamentPath+`/registrations/${registrationId}/check-in`,{method:'POST',cookie:scoreCookie})).status,403);
    assert.equal((await request(tournamentPath+'/registrations',{method:'POST',cookie,body:registrationBody})).status,409);
    const firstCheck=await request(tournamentPath+`/registrations/${registrationId}/check-in`,{method:'POST',cookie});assert.equal(firstCheck.status,200);
    const checkedAt=(await firstCheck.json()).checked_in_at;assert.ok(checkedAt);
    const repeatedCheck=await request(tournamentPath+`/registrations/${registrationId}/check-in`,{method:'POST',cookie});assert.equal(repeatedCheck.status,200);
    assert.equal((await repeatedCheck.json()).checked_in_at,checkedAt);
    const registrations=await request(tournamentPath+'/registrations',{cookie});assert.equal((await registrations.json()).registrations.length,1);
    const otherTournament=await request(path,{method:'POST',cookie,body:{...payload,name:'Other QA tournament'}});
    assert.equal(otherTournament.status,201);
    const otherTournamentId=(await otherTournament.json()).id;
    const otherPath=path+'/'+otherTournamentId;
    assert.equal((await request(otherPath+'/registrations',{method:'POST',cookie,body:registrationBody})).status,404);
    assert.equal((await request(otherPath+`/registrations/${registrationId}/check-in`,{method:'POST',cookie})).status,404);
    await assert.rejects(pool.query('INSERT INTO bowin_rebuild.registrations(id,organization_id,tournament_id,competitor_id,division_id) VALUES($1,$2,$3,$4,$5)',[randomUUID(),organizationId,otherTournamentId,competitorId,divisionId]),error=>error.code==='23503');
    const foreign=randomUUID();
    await pool.query('INSERT INTO bowin_rebuild.organizations(id,name) VALUES($1,$2)',[foreign,'Other QA club']);
    const foreignPath=`/api/organizations/${foreign}/tournaments`;
    assert.equal((await request(foreignPath,{cookie})).status,404);
    assert.equal((await request(foreignPath,{method:'POST',cookie,body:payload})).status,404);
    for(const suffix of ['divisions','competitors','registrations'])assert.equal((await request(foreignPath+'/'+tournamentId+'/'+suffix,{cookie})).status,404);
    assert.equal((await request(foreignPath+`/${tournamentId}/schedule`,{cookie})).status,404);
    // A valid invitation cannot replace an existing account's password.
    const ownerInvite=await request(invitePath,{method:'POST',cookie,body:{email:fixture.email,role:'organizer'}});assert.equal(ownerInvite.status,201);
    const ownerInviteToken=(await ownerInvite.json()).inviteUrl.split('#')[1];
    assert.equal((await request('/api/auth/accept-invite',{method:'POST',body:{token:ownerInviteToken,name:'Malicious replacement',password:'DifferentPassword-123456'}})).status,401);
    assert.equal((await pool.query('SELECT accepted_at FROM bowin_rebuild.invites WHERE token_hash=$1',[await import('../src/security.mjs').then(m=>m.tokenHash(ownerInviteToken))])).rows[0].accepted_at,null);
    const expired=await request(invitePath,{method:'POST',cookie,body:{email:'expired@example.invalid',role:'organizer'}});assert.equal(expired.status,201);
    const expiredToken=(await expired.json()).inviteUrl.split('#')[1];
    await pool.query("UPDATE bowin_rebuild.invites SET expires_at=now()-interval '1 second' WHERE email='expired@example.invalid'");
    assert.equal((await request('/api/auth/accept-invite',{method:'POST',body:{token:expiredToken,name:'Expired user',password:'ExpiredPassword-123456'}})).status,404);
    const seeds=[competitorId],pendingRegistrations=[];
    for(const label of ['B','C']){
      const next=await request(tournamentPath+'/competitors',{method:'POST',cookie,body:{name:'Private QA '+label,club:'QA club',publicDisplayName:'QA athlete '+label}});
      assert.equal(next.status,201);const nextId=(await next.json()).id;seeds.push(nextId);
      const registered=await request(tournamentPath+'/registrations',{method:'POST',cookie,body:{competitorId:nextId,divisionId}});
      assert.equal(registered.status,201);pendingRegistrations.push((await registered.json()).id);
    }
    const bracketPath=tournamentPath+`/divisions/${divisionId}/bracket`;
    assert.equal((await request(bracketPath,{method:'POST',cookie,body:{competitorIds:seeds}})).status,409);
    for(const id of pendingRegistrations)assert.equal((await request(tournamentPath+`/registrations/${id}/check-in`,{method:'POST',cookie})).status,200);
    assert.equal((await request(bracketPath,{method:'POST',cookie:scoreCookie,body:{competitorIds:seeds}})).status,403);
    const generated=await request(bracketPath,{method:'POST',cookie,body:{competitorIds:seeds}});assert.equal(generated.status,201);
    const generatedMatches=(await generated.json()).matches;
    assert.equal(generatedMatches[0].status,'bye');assert.equal(generatedMatches[2].status,'waiting');
    assert.equal((await request(bracketPath,{method:'POST',cookie,body:{competitorIds:seeds}})).status,409);
    assert.equal((await request(bracketPath+'/score',{method:'POST',cookie:scoreCookie,body:{matchKey:'2:1',scoreLeft:2,scoreRight:0}})).status,409);
    const semifinal={matchKey:'1:2',scoreLeft:0,scoreRight:2};
    const raced=await Promise.all([request(bracketPath+'/score',{method:'POST',cookie:scoreCookie,body:semifinal}),request(bracketPath+'/score',{method:'POST',cookie:scoreCookie,body:semifinal})]);
    assert.deepEqual(raced.map(response=>response.status).sort(),[200,409]);
    assert.equal((await request(foreignPath+`/${tournamentId}/divisions/${divisionId}/bracket/score`,{method:'POST',cookie:scoreCookie,body:{matchKey:'2:1',scoreLeft:1,scoreRight:0}})).status,404);
    const final=await request(bracketPath+'/score',{method:'POST',cookie:scoreCookie,body:{matchKey:'2:1',scoreLeft:3,scoreRight:1}});
    assert.equal(final.status,200);assert.equal((await final.json()).champion_id,competitorId);
    const persisted=await request(bracketPath,{cookie});assert.equal((await persisted.json()).champion_id,competitorId);
    const scoreAudit=(await pool.query("SELECT details FROM bowin_rebuild.audit_events WHERE action='match.scored' ORDER BY id DESC LIMIT 1")).rows[0].details;
    assert.deepEqual(scoreAudit,{matchKey:'2:1',scoreLeft:3,scoreRight:1,winnerId:competitorId});
    assert.equal((await request(schedulePath,{method:'POST',cookie,body:scheduleBody})).status,409);
    const privacyState=(await pool.query('SELECT publication_enabled,public_id FROM bowin_rebuild.tournaments WHERE id=$1',[tournamentId])).rows[0];
    assert.equal(privacyState.publication_enabled,false);assert.equal(privacyState.public_id,null);
    const publishPath=tournamentPath+'/publication';
    assert.equal((await request(publishPath,{method:'POST',cookie:scoreCookie,body:{published:true}})).status,403);
    const publication=await request(publishPath,{method:'POST',cookie,body:{published:true}});assert.equal(publication.status,200);
    const publicId=(await publication.json()).publicUrl.split('/').at(-1);
    const publicResponse=await request('/api/public/tournaments/'+publicId);assert.equal(publicResponse.status,200);
    assert.equal(publicResponse.headers.get('cache-control'),'no-store');
    const displayed=await publicResponse.json();
    assert.equal(displayed.organizer.name,fixture.organization);
    assert.equal(displayed.tournament.timeZone,'America/Toronto');
    const publicDivision=displayed.divisions.find(item=>item.name===divisionBody.name);
    assert.equal(publicDivision.champion,competitorBody.publicDisplayName);assert.equal(publicDivision.schedule.ring,'ring a');
    const serialized=JSON.stringify(displayed);
    for(const privateValue of [fixture.email,fixture.name,competitorBody.name,competitorBody.club,competitorId,divisionId,userId,'checked_in_by','token_hash','audit_events'])assert.ok(!serialized.includes(privateValue),`Public projection exposed ${privateValue}`);
    assert.equal((await request(publishPath,{method:'POST',cookie,body:{published:false}})).status,200);
    assert.equal((await request('/api/public/tournaments/'+publicId)).status,404);
    await pool.query("UPDATE bowin_rebuild.memberships SET role='scorekeeper' WHERE user_id=$1 AND organization_id=$2",[userId,organizationId]);
    assert.equal((await request(path,{method:'POST',cookie,body:payload})).status,403);
    for(const [suffix,body] of [['divisions',divisionBody],['competitors',competitorBody],['registrations',registrationBody],[`registrations/${registrationId}/check-in`,undefined]])assert.equal((await request(tournamentPath+'/'+suffix,{method:'POST',cookie,body})).status,403);
    assert.equal((await request('/api/auth/logout',{method:'POST',cookie})).status,200);
    assert.equal((await request('/api/me',{cookie})).status,401);
    const login=await request('/api/auth/login',{method:'POST',body:{email:fixture.email,password:fixture.password}});
    assert.equal(login.status,200);
    const loggedIn=login.headers.get('set-cookie').split(';')[0];
    await pool.query("UPDATE bowin_rebuild.sessions SET expires_at=now()-interval '1 second'");
    assert.equal((await request('/api/me',{cookie:loggedIn})).status,401);
    assert.equal((await pool.query('SELECT 1 FROM bowin_rebuild.audit_events')).rowCount,30);
  } finally {
    await new Promise(resolve=>server.close(resolve));await pool.end();
  }
});
