type UndoCandidate = { id: string; matchNumber: number; status: string; competitor1?: unknown; competitor2?: unknown };

function isScoredResult(match: UndoCandidate): boolean {
  if (match.status !== 'completed') return false;
  // Bye advancements (a missing competitor) are generated by the bracket,
  // have no result audit entry, and cannot be undone.
  if ('competitor1' in match || 'competitor2' in match) {
    return match.competitor1 != null && match.competitor2 != null;
  }
  return true;
}

/**
 * The match Ctrl+Z undoes. The result this station just recorded wins when it
 * is still completed; otherwise the highest-numbered scored match. Match
 * numbers alone are not chronological in double elimination (a losers-bracket
 * match can outnumber a later winners-bracket result).
 */
export function latestCompletedMatchId(matches: UndoCandidate[], preferredId: string | null = null): string | null {
  const scored = matches.filter(isScoredResult);
  if (preferredId && scored.some((match) => match.id === preferredId)) return preferredId;
  return scored.sort((a, b) => b.matchNumber - a.matchNumber)[0]?.id ?? null;
}
