import { useState, useRef, useEffect, useCallback } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useParams, Link } from 'react-router-dom';
import {
  ArrowLeft,
  RefreshCw,
  Download,
  Users,
  Trophy,
  Shuffle,
  Printer,
  Plus,
  X,
  ArrowLeftRight,
} from 'lucide-react';
import { CardSkeleton } from '../components/ui/Skeleton';
import ConfirmDialog from '../components/ui/ConfirmDialog';
import Spinner from '../components/ui/Spinner';
import { getAuthHeaders } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { Card, CardHeader, CardBody } from '../components/ui';
import { PageHeader } from '../components/ui';
import { Button } from '../components/ui';
import Modal from '../components/ui/Modal';
import OperationStatus, { type OperationState } from '../components/ui/OperationStatus';
import { useBracketWebSocket } from '../hooks/useBracketWebSocket';

interface Competitor {
  id: string;
  firstName: string;
  lastName: string;
  schoolDojang: string | null;
}

interface Registration {
  id: string;
  competitor: Competitor;
}

import type { ApiMatch } from '../../shared/contracts';

// BracketEditor extends ApiMatch with legacy competitor*Id fields
interface Match extends Omit<ApiMatch, 'competitor1' | 'competitor2' | 'winner'> {
  competitor1Id: string | null;
  competitor2Id: string | null;
  winnerId: string | null;
  competitor1: { competitor: Competitor } | null;
  competitor2: { competitor: Competitor } | null;
  winner: { competitor: Competitor } | null;
}

interface Bracket {
  id: string;
  format: string;
  structure: string;
  matches: Match[];
}

interface BracketCorrectionImpact {
  divisionLabel: string;
  competitorCount: number;
  oldFormat: string | null;
  newFormat: string;
  oldMatchCount: number;
  newMatchCount: number;
  completedMatchesRemoved: number;
  inProgressMatchesBlocked: number;
  scoredMatchesRemoved: number;
  notesRemoved: number;
  matchAuditRowsRemoved: number;
  matchupHistoryRowsRemoved: number;
  oldByeCount: number;
  newByeCount: number;
  changedFirstRoundPairings: Array<{ matchNumber: number; before: string[]; after: string[] }>;
}

interface BracketCorrectionPreview {
  proposedConfig: { format: 'double_elim' | 'single_elim' | 'round_robin' | 'pool_play'; seedingStrategy: 'school_spread' };
  impact: BracketCorrectionImpact;
  expectedInputVersion: string;
  expectedResultVersion: string;
  operationKey: string;
}

interface Division {
  id: string;
  name: string;
  beltLevel: string;
  gender: string;
  eventType: string;
  ageMin: number;
  ageMax: number;
  assignments: Array<{
    id: string;
    registration: Registration;
  }>;
  bracket: Bracket | null;
}

export default function BracketEditor() {
  const { tournamentId, divisionId } = useParams<{
    tournamentId: string;
    divisionId: string;
  }>();
  const queryClient = useQueryClient();
  const { addToast } = useToast();

  // Real-time WebSocket updates for bracket collaboration (P2-7)
  const { isConnected: wsConnected } = useBracketWebSocket({
    tournamentId: tournamentId || '',
    divisionId: divisionId || '',
    enabled: Boolean(tournamentId && divisionId),
    onMatchUpdate: (matchId) => {
      console.log(`[bracket-editor] Match ${matchId} updated by another user`);
    },
    onBracketRegenerated: () => {
      console.log('[bracket-editor] Bracket regenerated by another user');
      addToast('Bracket was regenerated. Reloading...', 'warning');
    },
  });

  const [showReseedConfirm, setShowReseedConfirm] = useState(false);
  const [correctionPreview, setCorrectionPreview] = useState<BracketCorrectionPreview | null>(null);
  const [correctionError, setCorrectionError] = useState('');
  const [correctionUncertain, setCorrectionUncertain] = useState(false);
  const [lastCorrection, setLastCorrection] = useState<{ auditId: string; operationKey: string } | null>(null);
  const [undoUncertain, setUndoUncertain] = useState(false);
  const [correctionNotice, setCorrectionNotice] = useState<{ state: OperationState; message: string } | null>(null);
  const previewCorrectionLockRef = useRef(false);
  const applyCorrectionLockRef = useRef(false);
  const undoCorrectionLockRef = useRef(false);
  const [pendingWinner, setPendingWinner] = useState<{ matchId: string; winnerId: string; name: string } | null>(null);

  const { data: division, isLoading } = useQuery<Division>({
    queryKey: ['division', divisionId],
    queryFn: async () => {
      const res = await fetch(`/api/divisions/${divisionId}`, { headers: getAuthHeaders() });
      if (!res.ok) throw new Error('Failed to fetch division');
      return res.json();
    },
  });

  const generateBracketMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`/api/brackets/division/${divisionId}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({ seedingStrategy: 'school_spread' }),
      });
      if (!res.ok) throw new Error('Failed to generate bracket');
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
    },
    onError: (error: Error) => {
      addToast(error.message || 'Operation failed', 'error');
    },
  });

  const previewCorrectionMutation = useMutation({
    mutationFn: async () => {
      const config = { format: (division?.bracket?.format ?? 'double_elim') as BracketCorrectionPreview['proposedConfig']['format'], seedingStrategy: 'school_spread' as const };
      const res = await fetch(`/api/brackets/division/${divisionId}/correction/preview`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({ config }),
      });
      const body = await res.json().catch(() => ({})) as BracketCorrectionPreview & { error?: string };
      if (!res.ok) throw new Error(body.error || 'Failed to preview bracket reseed');
      return body;
    },
    onMutate: () => {
      setCorrectionError('');
      setCorrectionNotice({ state: 'pending', message: 'Calculating the exact bracket and results affected.' });
    },
    onSuccess: (preview) => {
      setCorrectionPreview(preview);
      setShowReseedConfirm(true);
      setCorrectionNotice(null);
    },
    onError: (error: Error) => setCorrectionNotice({ state: 'rejected', message: error.message }),
    onSettled: () => { previewCorrectionLockRef.current = false; },
  });

  const applyCorrectionMutation = useMutation({
    mutationFn: async (preview: BracketCorrectionPreview) => {
      const res = await fetch(`/api/brackets/division/${divisionId}/correction/apply`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({
          config: preview.proposedConfig,
          expectedInputVersion: preview.expectedInputVersion,
          expectedResultVersion: preview.expectedResultVersion,
          operationKey: preview.operationKey,
        }),
      });
      const body = await res.json().catch(() => ({})) as { auditId?: string; error?: string };
      if (!res.ok) throw new Error(body.error || 'Failed to reseed bracket');
      if (!body.auditId) throw new Error('Bracket reseed acknowledgement was incomplete');
      return { auditId: body.auditId, operationKey: preview.operationKey };
    },
    onMutate: () => {
      setCorrectionError('');
      setCorrectionUncertain(false);
    },
    onSuccess: async (operation) => {
      await queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      setLastCorrection(operation);
      setShowReseedConfirm(false);
      setCorrectionPreview(null);
      setCorrectionNotice({ state: 'resolved', message: 'Bracket reseeded and reconciled with the server. Undo is available until scoring changes it.' });
    },
    onError: (error: Error) => {
      if (error instanceof TypeError) {
        setCorrectionUncertain(true);
        setCorrectionError('The server may have applied this reseed, but the response was lost. Check server status before taking another action.');
      } else setCorrectionError(error.message);
    },
    onSettled: () => { applyCorrectionLockRef.current = false; },
  });

  const correctionStatusMutation = useMutation({
    mutationFn: async (preview: BracketCorrectionPreview) => {
      const res = await fetch(`/api/brackets/division/${divisionId}/correction/status/${preview.operationKey}`, { headers: getAuthHeaders() });
      if (res.status === 404) return null;
      if (!res.ok) throw new Error('Could not check bracket correction status');
      return res.json() as Promise<{ auditId: string; applied: boolean; undone: boolean }>;
    },
    onSuccess: async (status) => {
      if (!status?.applied) {
        setCorrectionError('The reseed was not found on the server. Review the preview before trying again.');
        setCorrectionUncertain(false);
        return;
      }
      await queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      setLastCorrection({ auditId: status.auditId, operationKey: correctionPreview!.operationKey });
      setShowReseedConfirm(false);
      setCorrectionPreview(null);
      setCorrectionUncertain(false);
      setCorrectionNotice({ state: 'resolved', message: 'The server confirms the bracket reseed was applied. Undo is available until scoring changes it.' });
    },
    onError: (error: Error) => setCorrectionError(error.message),
  });

  const undoCorrectionMutation = useMutation({
    mutationFn: async (operation: { auditId: string; operationKey: string }) => {
      const res = await fetch(`/api/brackets/division/${divisionId}/correction/undo/${operation.auditId}`, { method: 'POST', headers: getAuthHeaders() });
      const body = await res.json().catch(() => ({})) as { error?: string };
      if (!res.ok) throw new Error(body.error || 'Failed to undo bracket reseed');
    },
    onMutate: () => setUndoUncertain(false),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      setLastCorrection(null);
      setCorrectionNotice({ state: 'resolved', message: 'The previous bracket, results, and correction history were restored.' });
    },
    onError: (error: Error) => {
      if (error instanceof TypeError) {
        setUndoUncertain(true);
        setCorrectionNotice({ state: 'rejected', message: 'Undo may have succeeded, but the response was lost. Check server status before retrying.' });
      } else setCorrectionNotice({ state: 'rejected', message: error.message });
    },
    onSettled: () => { undoCorrectionLockRef.current = false; },
  });

  const undoStatusMutation = useMutation({
    mutationFn: async (operation: { auditId: string; operationKey: string }) => {
      const res = await fetch(`/api/brackets/division/${divisionId}/correction/status/${operation.operationKey}`, { headers: getAuthHeaders() });
      if (!res.ok) throw new Error('Could not check undo status');
      return res.json() as Promise<{ undone: boolean }>;
    },
    onSuccess: async (status) => {
      if (!status.undone) {
        setUndoUncertain(false);
        setCorrectionNotice({ state: 'rejected', message: 'The server confirms undo was not applied. You may review and try Undo reseed again.' });
        return;
      }
      await queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      setUndoUncertain(false);
      setLastCorrection(null);
      setCorrectionNotice({ state: 'resolved', message: 'The previous bracket, results, and correction history were restored.' });
    },
    onError: (error: Error) => setCorrectionNotice({ state: 'rejected', message: error.message }),
  });

  const updateMatchMutation = useMutation({
    mutationFn: async ({
      matchId,
      winnerId,
    }: {
      matchId: string;
      winnerId: string;
    }) => {
      const res = await fetch(`/api/brackets/match/${matchId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({ winnerId, status: 'completed' }),
      });
      if (!res.ok) throw new Error('Failed to update match');
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
    },
    onError: (error: Error) => {
      addToast(error.message || 'Operation failed', 'error');
    },
  });

  const resetBracketMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`/api/brackets/division/${divisionId}/reset`, {
        method: 'POST',
        headers: getAuthHeaders(),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error((body as { error?: string }).error || 'Failed to reset bracket');
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
    },
    onError: (error: Error) => {
      addToast(error.message || 'Operation failed', 'error');
    },
  });

  // Swap the two competitors in a match. Closes H2 from the UI audit —
  // directors can now manually fix a bad auto-seed (e.g. two best
  // kids landing in the same half of the bracket) without losing all
  // completed matches. Backend at POST /api/brackets/match/:id/swap
  // just exchanges competitor1Id and competitor2Id.
  const swapMutation = useMutation({
    mutationFn: async (matchId: string) => {
      const res = await fetch(`/api/brackets/match/${matchId}/swap`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
      });
      if (!res.ok) throw new Error('Failed to swap competitors');
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      addToast?.('Competitors swapped.', 'success');
    },
    onError: (error: Error) => {
      addToast(error.message || 'Swap failed', 'error');
    },
  });

  // Pull all the tournament's registrations that AREN'T already
  // assigned to this division, so the director can drop late entries
  // into the bracket via the "+ Add" picker.
  const { data: unassignedData } = useQuery<{ registrations: Array<{ id: string; competitor: Competitor }> }>({
    queryKey: ['unassigned-registrations', tournamentId, divisionId],
    queryFn: async () => {
      const r = await fetch(
        `/api/tournaments/${tournamentId}/registrations?notInDivision=${divisionId}`,
        { headers: getAuthHeaders() },
      );
      if (!r.ok) return { registrations: [] };
      return r.json();
    },
    enabled: !!division && !!tournamentId,
  });

  const [showAddPicker, setShowAddPicker] = useState(false);
  const addCompetitorMutation = useMutation({
    mutationFn: async (registrationId: string) => {
      const res = await fetch(`/api/divisions/${divisionId}/assign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({ registrationId }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Add failed (${res.status})`);
      }
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      queryClient.invalidateQueries({ queryKey: ['unassigned-registrations', tournamentId, divisionId] });
      addToast?.('Competitor added to division. Regenerate bracket to include them.', 'success');
    },
    onError: (error: Error) => {
      addToast(error.message || 'Add failed', 'error');
    },
  });

  const removeCompetitorMutation = useMutation({
    mutationFn: async (assignmentId: string) => {
      const res = await fetch(`/api/divisions/${divisionId}/assign/${assignmentId}`, {
        method: 'DELETE',
        headers: getAuthHeaders(),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Remove failed (${res.status})`);
      }
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['division', divisionId] });
      queryClient.invalidateQueries({ queryKey: ['unassigned-registrations', tournamentId, divisionId] });
      addToast?.('Removed from division. Regenerate bracket if needed.', 'success');
    },
    onError: (error: Error) => {
      addToast(error.message || 'Remove failed', 'error');
    },
  });

  const exportPDF = async () => {
    if (!division) return;
    try {
      const res = await fetch(`/api/brackets/division/${divisionId}/pdf`, { headers: getAuthHeaders() });
      if (!res.ok) throw new Error('Failed to generate PDF');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${division.name.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      addToast('Error exporting PDF. Please try again.', 'error');
    }
  };

  // All hooks must be declared BEFORE any early returns so the hook order is
  // stable across renders. (See the Rules of Hooks — early returns below
  // these hooks would otherwise fire on a different number of hooks per
  // render, causing "Rendered more hooks than during the previous render".)

  // Roving-tabindex keyboard navigation for the bracket grid.
  // The "grid" is organised: each column = a round, each match within a column
  // is stacked vertically. Adjacent rounds have different match counts, so
  // we use a simple 1D pattern that maps cleanly:
  //   - Left / Right: previous / next match within the same round
  //   - Up / Down: previous / next round (focus the match at the same vertical
  //                position if it exists, else clamp to the nearest match)
  //   - Tab / Shift+Tab: next / previous cell in the bracket as a flat list
  // The first cell of the first column starts as the only tabbable cell; after
  // any focus event inside the grid we update tabindex via the effect below.
  const bracketGridRef = useRef<HTMLDivElement>(null);
  const handleBracketKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLDivElement>) => {
      const grid = bracketGridRef.current;
      if (!grid) return;
      const target = e.target as HTMLElement;
      if (!target.matches('[data-bracket-cell]')) return;
      const cell = target.closest<HTMLElement>('[data-bracket-cell]');
      if (!cell) return;

      const allCells = Array.from(
        grid.querySelectorAll<HTMLElement>('[data-bracket-cell]')
      );
      // Group cells by column. Within a column they're in DOM order.
      const byCol = new Map<number, HTMLElement[]>();
      for (const el of allCells) {
        const c = parseInt(el.dataset.col ?? '-1', 10);
        if (c < 0) continue;
        if (!byCol.has(c)) byCol.set(c, []);
        byCol.get(c)!.push(el);
      }
      const cols = Array.from(byCol.keys()).sort((a, b) => a - b);
      if (cols.length === 0) return;

      const col = parseInt(cell.dataset.col ?? '-1', 10);
      const cellsInCol = byCol.get(col) ?? [];
      const idxInCol = cellsInCol.indexOf(cell);

      const tryFocus = (el: HTMLElement | undefined) => {
        if (el) {
          e.preventDefault();
          el.focus();
        }
      };

      if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        const dir = e.key === 'ArrowLeft' ? -1 : 0; // Up moves to previous round
        if (e.key === 'ArrowLeft') {
          // Previous match within the same round.
          tryFocus(cellsInCol[idxInCol - 1]);
        } else {
          const nextColIdx = cols.indexOf(col) - 1;
          if (nextColIdx < 0) return;
          const nextCol = cols[nextColIdx];
          const nextColCells = byCol.get(nextCol) ?? [];
          // Pick the cell at the same vertical position, clamped.
          const targetIdx = Math.min(idxInCol, nextColCells.length - 1);
          tryFocus(nextColCells[targetIdx]);
        }
        return;
      }
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        if (e.key === 'ArrowRight') {
          tryFocus(cellsInCol[idxInCol + 1]);
        } else {
          const nextColIdx = cols.indexOf(col) + 1;
          if (nextColIdx >= cols.length) return;
          const nextCol = cols[nextColIdx];
          const nextColCells = byCol.get(nextCol) ?? [];
          const targetIdx = Math.min(idxInCol, nextColCells.length - 1);
          tryFocus(nextColCells[targetIdx]);
        }
        return;
      }
    },
    []
  );

  // Sync the roving tabindex: the first cell of the first column is the tab stop,
  // all others are tabindex=-1. After any focus event, recompute which cell is the active one.
  useEffect(() => {
    const grid = bracketGridRef.current;
    if (!grid) return;
    const cells = Array.from(grid.querySelectorAll<HTMLElement>('[data-bracket-cell]'));
    if (cells.length === 0) return;

    const setActive = (el: HTMLElement) => {
      cells.forEach((c) => {
        if (c === el) c.setAttribute('tabindex', '0');
        else c.setAttribute('tabindex', '-1');
      });
    };

    // Initial: first cell is tabbable, rest are not.
    setActive(cells[0]);
    const onFocusIn = (e: Event) => {
      const t = e.target as HTMLElement;
      if (t.matches('[data-bracket-cell]')) setActive(t);
    };
    grid.addEventListener('focusin', onFocusIn);
    return () => grid.removeEventListener('focusin', onFocusIn);
  }, [division?.bracket?.id]);

  // Live region announcement for bracket update success/failure.
  const [bracketAnnounce, setBracketAnnounce] = useState('');
  useEffect(() => {
    if (updateMatchMutation.isSuccess) {
      setBracketAnnounce('Winner recorded. Bracket updated.');
    }
  }, [updateMatchMutation.isSuccess]);
  useEffect(() => {
    if (updateMatchMutation.isError) {
      setBracketAnnounce(
        `Failed to record winner: ${(updateMatchMutation.error as Error)?.message ?? 'Unknown error'}`
      );
    }
  }, [updateMatchMutation.isError]);

  if (isLoading) {
    return (
      <div className="space-y-6">
        <CardSkeleton />
        <CardSkeleton />
      </div>
    );
  }

  if (!division) {
    return (
      <div className="text-center py-12">
        <div className="text-surface-600 dark:text-surface-400">Division not found</div>
      </div>
    );
  }

  const winnersMatches =
    division.bracket?.matches?.filter((m) => m.bracketType === 'winners') || [];
  const losersMatches =
    division.bracket?.matches?.filter((m) => m.bracketType === 'losers') || [];
  const finalsMatches =
    division.bracket?.matches?.filter((m) => m.bracketType === 'finals') || [];

  // Sort each bracket by (roundNumber, matchNumber) so we can derive a stable
  // 1-indexed per-bracket position. The display label uses this position so
  // losers matches restart numbering at 1 (L1, L2, ...) instead of continuing
  // the global matchNumber from the winners bracket.
  const sortBracket = (arr: Match[]) =>
    [...arr].sort((a, b) => a.roundNumber - b.roundNumber || a.matchNumber - b.matchNumber);

  const winnersMatchesSorted = sortBracket(winnersMatches);
  const losersMatchesSorted = sortBracket(losersMatches);
  const finalsMatchesSorted = sortBracket(finalsMatches);

  // Build a lookup: match.id -> display label. Winners/Losers restart at 1;
  // Finals are labeled "GF" (Grand Finals). Falls back to the raw matchNumber
  // if the bracketType is unknown.
  const matchLabelById = new Map<string, string>();
  winnersMatchesSorted.forEach((m, i) => matchLabelById.set(m.id, `W${i + 1}`));
  losersMatchesSorted.forEach((m, i) => matchLabelById.set(m.id, `L${i + 1}`));
  finalsMatchesSorted.forEach((m) => matchLabelById.set(m.id, 'GF'));
  const getMatchLabel = (match: Match) =>
    matchLabelById.get(match.id) ?? `M${match.matchNumber}`;

  const winnersRounds = [...new Set(winnersMatches.map(m => m.roundNumber))].sort((a, b) => a - b);
  const losersRounds = [...new Set(losersMatches.map(m => m.roundNumber))].sort((a, b) => a - b);

  const handleSelectWinner = (matchId: string, winnerId: string, match: Match) => {
    const comp = match.competitor1Id === winnerId ? match.competitor1 : match.competitor2;
    const name = comp
      ? `${comp.competitor.firstName} ${comp.competitor.lastName}`
      : 'Unknown';
    setPendingWinner({ matchId, winnerId, name });
  };

  return (
    <div className="space-y-6">
      {correctionNotice && (
        <OperationStatus
          state={correctionNotice.state}
          message={correctionNotice.message}
          actionLabel={undoUncertain ? 'Check undo status' : lastCorrection && correctionNotice.state === 'resolved' ? 'Undo reseed' : undefined}
          onAction={lastCorrection ? () => {
            if (undoUncertain) undoStatusMutation.mutate(lastCorrection);
            else if (!undoCorrectionLockRef.current) {
              undoCorrectionLockRef.current = true;
              undoCorrectionMutation.mutate(lastCorrection);
            }
          } : undefined}
        />
      )}
      {/* Page Header */}
      <PageHeader
        title={division.name}
        description={`${division.assignments.length} competitors`}
        actions={
          <div className="flex gap-2 sm:gap-3">
            {division.bracket ? (
              <>
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => {
                    if (previewCorrectionLockRef.current) return;
                    previewCorrectionLockRef.current = true;
                    previewCorrectionMutation.mutate();
                  }}
                  loading={previewCorrectionMutation.isPending}
                  aria-label="Reseed bracket"
                >
                  <Shuffle className="h-4 w-4 mr-2" aria-hidden="true" />
                  <span className="hidden sm:inline">Reseed</span>
                </Button>
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={exportPDF}
                  aria-label={`Export ${division.name} bracket as PDF`}
                >
                  <Download className="h-4 w-4 mr-2" aria-hidden="true" />
                  <span className="hidden sm:inline">Export PDF</span>
                </Button>
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => window.print()}
                  aria-label={`Print ${division.name} bracket`}
                >
                  <Printer className="h-4 w-4 mr-2" aria-hidden="true" />
                  <span className="hidden sm:inline">Print</span>
                </Button>
              </>
            ) : (
              <Button
                variant="primary"
                size="sm"
                onClick={() => generateBracketMutation.mutate()}
                loading={generateBracketMutation.isPending}
                aria-label={`Generate bracket for ${division.name}`}
              >
                <RefreshCw className="h-4 w-4 mr-2" aria-hidden="true" /> Generate Bracket
              </Button>
            )}
          </div>
        }
      />

      {/* Back link */}
      <Link
        to={`/tournaments/${tournamentId}/divisions`}
        className="text-sm text-surface-600 dark:text-surface-400 hover:text-surface-700 dark:hover:text-surface-300 flex items-center"
        aria-label="Back to Divisions"
      >
        <ArrowLeft className="h-4 w-4 mr-1" aria-hidden="true" /> Back to Divisions
      </Link>

      {/* Competitors List */}
      <Card>
        <CardHeader
          title={`Competitors (${division.assignments.length})`}
          action={
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="secondary"
                onClick={() => setShowAddPicker((v) => !v)}
                aria-label="Add a competitor from the tournament's unassigned registrations"
              >
                <Plus className="h-4 w-4 mr-1" />
                Add
              </Button>
              <Users className="h-5 w-5 text-primary-600 dark:text-primary-400" />
            </div>
          }
        />
        <CardBody>
          {/* Inline "Add competitor" picker. Shows registrations registered
              to the same tournament but not yet assigned to this division.
              Closes H2 from the UI audit — directors can fix a kid who
              showed up unregistered without rebuilding everything. */}
          {showAddPicker && (
            <div className="mb-3 p-3 rounded-lg border border-primary-200 dark:border-primary-800 bg-primary-50 dark:bg-primary-900/30">
              <div className="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300 mb-2">
                Add from this tournament
              </div>
              {unassignedData?.registrations && unassignedData.registrations.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {unassignedData.registrations.map((r) => (
                    <Button
                      key={r.id}
                      size="sm"
                      variant="secondary"
                      loading={addCompetitorMutation.isPending && addCompetitorMutation.variables === r.id}
                      onClick={() => addCompetitorMutation.mutate(r.id)}
                    >
                      + {r.competitor.firstName} {r.competitor.lastName}
                      {r.competitor.schoolDojang && <span className="text-xs ml-1 opacity-70">({r.competitor.schoolDojang})</span>}
                    </Button>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-surface-600 dark:text-surface-400">
                  Every registered competitor is already assigned to a division.
                </p>
              )}
            </div>
          )}
          <div className="flex flex-wrap gap-2">
            {division.assignments.map((a, i) => (
              <span
                key={a.id}
                className="inline-flex items-center px-3 py-1 rounded-full text-sm bg-surface-100 dark:bg-surface-700 text-surface-900 dark:text-surface-100 gap-2"
              >
                <span className="font-medium mr-1">{i + 1}.</span>
                {a.registration.competitor.firstName}{' '}
                {a.registration.competitor.lastName}
                {a.registration.competitor.schoolDojang && (
                  <span className="ml-1 text-surface-600 dark:text-surface-400 text-xs">
                    ({a.registration.competitor.schoolDojang})
                  </span>
                )}
                <button
                  type="button"
                  onClick={() => {
                    if (confirm(`Remove ${a.registration.competitor.firstName} ${a.registration.competitor.lastName} from this division? Their bracket slot will be freed; regenerate the bracket to refill.`)) {
                      removeCompetitorMutation.mutate(a.id);
                    }
                  }}
                  aria-label={`Remove ${a.registration.competitor.firstName} ${a.registration.competitor.lastName} from this division`}
                  className="ml-1 text-surface-500 hover:text-danger600 dark:hover:text-danger400 focus:outline-none focus:ring-2 focus:ring-red-500 rounded-full"
                >
                  <X className="h-3.5 w-3.5" aria-hidden="true" />
                </button>
              </span>
            ))}
          </div>
        </CardBody>
      </Card>

      {/* Bracket Visualization */}
      {division.bracket ? (
        <Card>
          <CardHeader
            title="Bracket"
            action={<Trophy className="h-5 w-5 text-primary-600 dark:text-primary-400" aria-hidden="true" />}
          />
          <CardBody className="overflow-x-auto">
            <div
              ref={bracketGridRef}
              role="grid"
              aria-label={`${division.name} bracket — use arrow keys to move between matches`}
              onKeyDown={handleBracketKeyDown}
            >
            {/* Winners / Losers / Grand Finals sections — all rendered as
                horizontal columns (rounds left-to-right, matches stacked
                vertically within each round column) via the shared
                <BracketSection> component. Adding the same component to all
                three sections guarantees the losers bracket cannot drift
                out of alignment with the winners layout. */}
            <div className="bracket-print-root">
            <BracketSection
              ariaLabel="Winners bracket"
              title="Winners Bracket"
              rounds={winnersRounds}
              matches={winnersMatches}
              colOffset={0}
              getMatchLabel={getMatchLabel}
              onSelectWinner={handleSelectWinner}
              onSwap={(matchId) => {
                if (confirm('Swap the two competitors in this match? Used to fix a bad auto-seed (e.g. two best kids landing in the same half).')) {
                  swapMutation.mutate(matchId);
                }
              }}
            />

            {losersRounds.length > 0 && (
              <BracketSection
                ariaLabel="Losers bracket"
                title="Losers Bracket"
                rounds={losersRounds}
                matches={losersMatches}
                colOffset={winnersRounds.length}
                getMatchLabel={getMatchLabel}
                onSelectWinner={handleSelectWinner}
                onSwap={(matchId) => {
                  if (confirm('Swap the two competitors in this match?')) {
                    swapMutation.mutate(matchId);
                  }
                }}
              />
            )}

            {finalsMatches.length > 0 && (
              <BracketSection
                ariaLabel="Grand finals"
                title="Grand Finals"
                subtitle="After Losers Final"
                rounds={[0]}
                matches={finalsMatches}
                colOffset={winnersRounds.length + losersRounds.length}
                getMatchLabel={getMatchLabel}
                onSelectWinner={handleSelectWinner}
                onSwap={(matchId) => {
                  if (confirm('Swap the two competitors in this match?')) {
                    swapMutation.mutate(matchId);
                  }
                }}
                showMatchLabels
                matchLabelPrefix="Match"
              />
            )}
            </div>
            </div>
          </CardBody>
        </Card>
      ) : (
        <Card>
          <CardBody className="text-center py-12">
            <Trophy className="mx-auto h-12 w-12 text-surface-600 dark:text-surface-500" aria-hidden="true" />
            <h3 className="mt-2 text-sm font-medium text-surface-900 dark:text-white">
              No bracket generated
            </h3>
            <p className="mt-1 text-sm text-surface-600 dark:text-surface-400">
              Generate a bracket to start the competition.
            </p>
            <Button
              variant="primary"
              className="mt-4"
              onClick={() => generateBracketMutation.mutate()}
              loading={generateBracketMutation.isPending}
              aria-label={`Generate bracket for ${division.name}`}
            >
              Generate Bracket
            </Button>
          </CardBody>
        </Card>
      )}

      {/* Reseed impact and correction dialog */}
      <Modal
        isOpen={showReseedConfirm}
        onClose={() => {
          if (applyCorrectionMutation.isPending || correctionStatusMutation.isPending || correctionUncertain) return;
          setShowReseedConfirm(false);
          setCorrectionPreview(null);
          setCorrectionError('');
          setCorrectionUncertain(false);
        }}
        closeDisabled={applyCorrectionMutation.isPending || correctionStatusMutation.isPending || correctionUncertain}
        title="Regenerate Bracket"
        subtitle="Review the exact impact before replacing the bracket."
        footer={
          <div className="flex w-full justify-end gap-3">
            <Button variant="secondary" onClick={() => setShowReseedConfirm(false)} disabled={applyCorrectionMutation.isPending || correctionStatusMutation.isPending || correctionUncertain}>Cancel</Button>
            {correctionUncertain ? (
              <Button variant="primary" onClick={() => correctionPreview && correctionStatusMutation.mutate(correctionPreview)} loading={correctionStatusMutation.isPending}>Check server status</Button>
            ) : (
              <Button
                variant="danger"
                onClick={() => {
                  if (!correctionPreview || applyCorrectionLockRef.current) return;
                  applyCorrectionLockRef.current = true;
                  applyCorrectionMutation.mutate(correctionPreview);
                }}
                loading={applyCorrectionMutation.isPending}
                disabled={!correctionPreview || correctionPreview.impact.inProgressMatchesBlocked > 0}
              >Apply reseed</Button>
            )}
          </div>
        }
      >
        {correctionPreview && (
          <div className="space-y-4 text-sm">
            {correctionError && <OperationStatus state="rejected" message={correctionError} />}
            <p>This correction replaces <strong>{correctionPreview.impact.oldMatchCount}</strong> matches with <strong>{correctionPreview.impact.newMatchCount}</strong> for {correctionPreview.impact.competitorCount} competitors.</p>
            <dl className="grid grid-cols-2 gap-3 rounded-xl bg-surface-50 p-4 dark:bg-surface-900">
              <div><dt className="text-surface-500">Completed results</dt><dd className="font-semibold">{correctionPreview.impact.completedMatchesRemoved}</dd></div>
              <div><dt className="text-surface-500">Scored matches</dt><dd className="font-semibold">{correctionPreview.impact.scoredMatchesRemoved}</dd></div>
              <div><dt className="text-surface-500">Audit entries</dt><dd className="font-semibold">{correctionPreview.impact.matchAuditRowsRemoved}</dd></div>
              <div><dt className="text-surface-500">Match histories</dt><dd className="font-semibold">{correctionPreview.impact.matchupHistoryRowsRemoved}</dd></div>
              <div><dt className="text-surface-500">BYEs before</dt><dd className="font-semibold">{correctionPreview.impact.oldByeCount}</dd></div>
              <div><dt className="text-surface-500">BYEs after</dt><dd className="font-semibold">{correctionPreview.impact.newByeCount}</dd></div>
            </dl>
            {correctionPreview.impact.changedFirstRoundPairings.length > 0 && (
              <div>
                <h3 className="font-semibold">Changed first-round pairings</h3>
                <ul className="mt-2 space-y-2">
                  {correctionPreview.impact.changedFirstRoundPairings.map((pairing) => (
                    <li key={pairing.matchNumber} className="rounded-lg border p-3">Match {pairing.matchNumber}: {pairing.before.join(' vs ') || 'empty'} → {pairing.after.join(' vs ') || 'empty'}</li>
                  ))}
                </ul>
              </div>
            )}
            {correctionPreview.impact.inProgressMatchesBlocked > 0 ? (
              <OperationStatus state="rejected" message="A match is currently in progress. Finish or safely correct it before reseeding." />
            ) : (
              <p className="rounded-lg border border-warning300 bg-warning/50 p-3 text-warning950 dark:border-warning800 dark:bg-warning/950/40 dark:text-warning100">The current bracket, results, notes, and histories will be snapshotted. Undo remains available only until the replacement bracket is scored or otherwise changed.</p>
            )}
          </div>
        )}
      </Modal>

      {/* Winner Confirmation Dialog */}
      <ConfirmDialog
        isOpen={!!pendingWinner}
        onClose={() => setPendingWinner(null)}
        onConfirm={() => {
          if (pendingWinner) {
            updateMatchMutation.mutate({
              matchId: pendingWinner.matchId,
              winnerId: pendingWinner.winnerId,
            });
            setPendingWinner(null);
          }
        }}
        title="Confirm Winner"
        message={`Record ${pendingWinner?.name ?? ''} as the winner of this match?`}
        confirmText="Record Winner"
        variant="info"
        isLoading={updateMatchMutation.isPending}
      />

      {/* Live region for bracket update announcements. */}
      <div role="status" aria-live="polite" aria-atomic="true" className="sr-only">
        {bracketAnnounce}
      </div>
    </div>
  );
}

/**
 * Render one bracket section (Winners, Losers, or Grand Finals) as a
 * horizontal row of round columns, with matches stacked vertically inside
 * each column. Shared by all three sections so the Losers bracket cannot
 * drift out of horizontal alignment with the Winners bracket.
 */
function BracketSection({
  ariaLabel,
  title,
  subtitle,
  rounds,
  matches,
  colOffset,
  getMatchLabel,
  onSelectWinner,
  onSwap,
  showMatchLabels = false,
  matchLabelPrefix = 'Match',
}: {
  ariaLabel: string;
  title: string;
  subtitle?: string;
  rounds: number[];
  matches: Match[];
  colOffset: number;
  getMatchLabel: (match: Match) => string;
  onSelectWinner: (matchId: string, winnerId: string, match: Match) => void;
  onSwap?: (matchId: string) => void;
  showMatchLabels?: boolean;
  matchLabelPrefix?: string;
}) {
  // Group matches by round so each column gets its own list. For Grand
  // Finals (rounds=[0]) we just dump every match into a single column.
  const matchesByRound = new Map<number, Match[]>();
  matches.forEach((m) => {
    const key = rounds.length === 1 ? 0 : m.roundNumber;
    const list = matchesByRound.get(key) ?? [];
    list.push(m);
    matchesByRound.set(key, list);
  });

  return (
    <div className="mb-8 last:mb-0" role="rowgroup" aria-label={ariaLabel}>
      <h4
        className={`text-sm font-semibold text-surface-700 dark:text-surface-300 ${
          subtitle ? 'mb-1' : 'mb-4'
        }`}
      >
        {title}
      </h4>
      {subtitle && (
        <p className="text-xs text-surface-600 dark:text-surface-400 mb-4">
          {subtitle}
        </p>
      )}
      <div className="flex gap-8">
        {rounds.map((round, colIdx) => {
          const columnMatches = matchesByRound.get(round) ?? [];
          return (
            <div
              key={round}
              className="min-w-max space-y-4"
              role="row"
              aria-label={
                rounds.length === 1 ? ariaLabel : `${ariaLabel} round ${round}`
              }
            >
              {rounds.length > 1 && (
                <div className="text-xs text-surface-600 dark:text-surface-400 text-center mb-2">
                  Round {round}
                </div>
              )}
              {columnMatches.map((match) => (
                <MatchCard
                  key={match.id}
                  match={match}
                  label={getMatchLabel(match)}
                  bracketCol={colOffset + colIdx}
                  onSelectWinner={(winnerId) =>
                    onSelectWinner(match.id, winnerId, match)
                  }
                  onSwap={onSwap ? () => onSwap(match.id) : undefined}
                />
              ))}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function MatchCard({
  match,
  bracketCol,
  onSelectWinner,
  onSwap,
  label,
}: {
  match: Match;
  bracketCol: number;
  onSelectWinner: (winnerId: string) => void;
  onSwap?: () => void;
  label: string;
}) {
  const name1 = match.competitor1
    ? `${match.competitor1.competitor.firstName} ${match.competitor1.competitor.lastName}`
    : match.competitor1Id
    ? 'TBD'
    : 'BYE';

  const name2 = match.competitor2
    ? `${match.competitor2.competitor.firstName} ${match.competitor2.competitor.lastName}`
    : match.competitor2Id
    ? 'TBD'
    : 'BYE';

  const isReady = match.competitor1Id && match.competitor2Id && !match.winnerId;
  const isComplete = !!match.winnerId;
  const cardStatus = isComplete ? 'complete' : isReady ? 'ready' : match.status;

  return (
    <div
      className={`w-48 border rounded-lg overflow-hidden ${
        isComplete
          ? 'border-success300 dark:border-success700 bg-success/50 dark:bg-success/900/30'
          : isReady
          ? 'border-warning300 dark:border-warning700 bg-warning/50 dark:bg-warning/900/30'
          : 'border-surface-200 dark:border-surface-700 bg-white dark:bg-surface-800'
      }`}
    >
      <div className="px-2 py-1 bg-surface-100 dark:bg-surface-700 text-xs text-surface-700 dark:text-surface-400 flex justify-between">
        <span>Match {label}</span>
        <span className="capitalize" aria-label={`Status: ${cardStatus}`}>{cardStatus}</span>
      </div>
      <div className="divide-y divide-surface-200 dark:divide-surface-700">
        <button
          onClick={() =>
            isReady && match.competitor1Id && onSelectWinner(match.competitor1Id)
          }
          disabled={!isReady}
          data-bracket-cell="true"
          data-col={bracketCol}
          data-row={0}
          aria-pressed={match.winnerId === match.competitor1Id}
          aria-label={
            `Match ${label}, ${name1}` +
            (match.winnerId === match.competitor1Id ? ' (winner)' : '') +
            (isReady ? ' — press Enter to record as winner' : '')
          }
          className={`w-full px-3 py-2 text-left text-sm truncate text-surface-900 dark:text-surface-100 focus:outline-none focus:ring-2 focus:ring-primary-500 ${
            match.winnerId === match.competitor1Id
              ? 'bg-success/100 dark:bg-success/800/50 font-semibold'
              : isReady
              ? 'hover:bg-surface-50 dark:hover:bg-surface-700'
              : ''
          }`}
        >
          {name1}
          {match.competitor1?.competitor.schoolDojang && (
            <span className="text-xs text-surface-600 dark:text-surface-500 ml-1">
              ({match.competitor1.competitor.schoolDojang.substring(0, 20)})
            </span>
          )}
        </button>
        <button
          onClick={() =>
            isReady && match.competitor2Id && onSelectWinner(match.competitor2Id)
          }
          disabled={!isReady}
          data-bracket-cell="true"
          data-col={bracketCol}
          data-row={1}
          aria-pressed={match.winnerId === match.competitor2Id}
          aria-label={
            `Match ${label}, ${name2}` +
            (match.winnerId === match.competitor2Id ? ' (winner)' : '') +
            (isReady ? ' — press Enter to record as winner' : '')
          }
          className={`w-full px-3 py-2 text-left text-sm truncate text-surface-900 dark:text-surface-100 focus:outline-none focus:ring-2 focus:ring-primary-500 ${
            match.winnerId === match.competitor2Id
              ? 'bg-success/100 dark:bg-success/800/50 font-semibold'
              : isReady
              ? 'hover:bg-surface-50 dark:hover:bg-surface-700'
              : ''
          }`}
        >
          {name2}
          {match.competitor2?.competitor.schoolDojang && (
            <span className="text-xs text-surface-600 dark:text-surface-500 ml-1">
              ({match.competitor2.competitor.schoolDojang.substring(0, 20)})
            </span>
          )}
        </button>
      </div>
      {onSwap && match.competitor1Id && match.competitor2Id && (
        <button
          onClick={onSwap}
          aria-label={`Swap competitors in match ${label}`}
          title="Swap competitors (useful for fixing a bad auto-seed)"
          className="w-full px-2 py-1 text-xs text-surface-500 dark:text-surface-400 hover:text-primary-600 dark:hover:text-primary-400 bg-surface-50 dark:bg-surface-700/50 border-t border-surface-200 dark:border-surface-700 focus:outline-none focus:ring-2 focus:ring-primary-500 flex items-center justify-center gap-1"
        >
          <ArrowLeftRight className="h-3 w-3" aria-hidden="true" />
          Swap
        </button>
      )}
    </div>
  );
}
